version: "2"

services:
  quassel-core:
    image: linuxserver/quassel-core
    container_name: quassel-core
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- RUN_OPTS=--config-from-environment
    volumes:
      - ./config:/config
    ports:
      - 4242:4242
    restart: unless-stopped
